
DROP TABLE Constructed;
DROP TABLE Constructor;
DROP TABLE ETCReading;
DROP TABLE Vehicle;
DROP TABLE TollGate;
DROP TABLE Tollway;
DROP TABLE Driver;

CREATE TABLE Driver (
	License INT NOT NULL,
	Ht FLOAT NOT NULL,
	Wt FLOAT NOT NULL,
	Eye VARCHAR(30) NOT NULL,
	Sex CHAR(1) NOT NULL,
	DOB DATETIME NOT NULL,
	Expiration DATE NOT NULL,
	Issued DATE NOT NULL,
	HomeAddress VARCHAR(30) NOT NULL,
	FullName VARCHAR(30) NOT NULL,
	CHECK (Expiration > Issued),
	PRIMARY KEY (License),
);

CREATE TABLE Tollway (
	ID INT UNIQUE,
	CYear INT NOT NULL,
	TWLength INT NOT NULL,
	NumLanes INT NOT NULL,
	PRIMARY KEY (ID),
);

CREATE TABLE TollGate (
	ID INT UNIQUE,
	TWID INT,
	TGLength INT NOT NULL,
	FOREIGN KEY (TWID) REFERENCES TollWay(ID),
	PRIMARY KEY (ID),
);

CREATE TABLE Vehicle (
	PlateNumber VARCHAR(10) UNIQUE,
	StateRegistered CHAR(2) NOT NULL,
	DateRegistered DATETIME NOT NULL,
	RegisteredExpDate DATETIME NOT NULL,
	TollRate MONEY,
	VehicleWeight FLOAT NOT NULL,
	License INT NOT NULL,
	ETag INT UNIQUE NOT NULL,
	FOREIGN KEY (License) REFERENCES Driver(License),
	CHECK (DateRegistered < RegisteredExpDate),
	PRIMARY KEY (PlateNumber),
);

CREATE TABLE ETCReading (
	ID INT UNIQUE NOT NULL,
	TGID INT NOT NULL,
	DTime DATETIME NOT NULL,
	ETag INT NOT NULL,
	FOREIGN KEY (TGID) REFERENCES  TollGate(ID),
	FOREIGN KEY (ETag) REFERENCES Vehicle(ETag),
	PRIMARY KEY (ID),
);

CREATE TABLE Constructor (
	ID INT NOT NULL,
	FullName VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID),
);

CREATE TABLE Constructed (
	TWID INT UNIQUE NOT NULL,
	CID INT UNIQUE NOT NULL,
	FOREIGN KEY (TWID) REFERENCES TollWay(ID),
	FOREIGN KEY (CID) REFERENCES Constructor(ID),
	PRIMARY KEY (TWID, CID),
);


